modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="petting"
version="4.0.0"
displayName="Petting"
displayURL="https://www.anchorstudios.site/wiki/petting"
credits="Thanks to respectful developers of Anchor Studios"
authors="Anchor Studios"
description="Pet mobs and have them become protective companions that follow you, offering support and assistance during your adventures."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.petting]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.petting]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.petting]]
    modId="ancore"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration