modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="petting"
version="3.0.1"
displayName="Petting"
displayURL="https://www.anchorstudios.site/wiki/petting"
credits="Thanks to respectful developers of Anchor Studios"
authors="Anchor Studios"
description="Pet mobs and have them become protective companions that follow you, offering support and assistance during your adventures."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.petting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.petting]]
    modId="ancore"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration